#!/usr/bin/env python3
"""Regenerate Sources/DaaDockTests/main.swift from the test files.

Command Line Tools ship no XCTest, so there is no runtime test discovery.
This walks the sources and writes the registration list out explicitly.
"""
import re, glob, os, collections, sys

here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
suites = collections.OrderedDict()
for path in sorted(glob.glob(os.path.join(here, 'Sources/DaaDockTests/*Tests.swift'))):
    cur = None
    for line in open(path):
        m = re.match(r'\s*(?:final\s+)?class\s+(\w+):\s*XCTestCase', line)
        if m:
            cur = m.group(1); suites[cur] = []
        m = re.match(r'\s*func\s+(test\w+)\s*\(\s*\)(\s*throws)?', line)
        if m and cur:
            suites[cur].append((m.group(1), bool(m.group(2))))

out = ['// GENERATED by tools/gen-tests.py -- do not edit by hand.',
       '// Regenerate after adding a test:  make -C ui gen-tests',
       'import Foundation', 'import MicroTest', '', 'let suites: [(String, [Test])] = [']
for cls, tests in suites.items():
    out.append(f'    ("{cls}", [')
    for name, throws in tests:
        call = f'try {cls}().{name}()' if throws else f'{cls}().{name}()'
        out.append(f'        Test("{name}") {{ {call} }},')
    out.append('    ]),')
out += [']', '', 'let filter = CommandLine.arguments.dropFirst().first',
        'exit(Runner.run(suites, filter: filter))', '']
open(os.path.join(here, 'Sources/DaaDockTests/main.swift'), 'w').write('\n'.join(out))
print(f"{sum(len(v) for v in suites.values())} tests across {len(suites)} suites", file=sys.stderr)
